Update build_and_release.yml

diff --git a/.github/workflows/build_and_release.yml b/.github/workflows/build_and_release.yml
--- a/.github/workflows/build_and_release.yml
+++ b/.github/workflows/build_and_release.yml
@@ -36,7 +36,11 @@ jobs:
         run: |
           echo "Compiling chrome_decrypt.dll for x64"
           cl /EHsc /std:c++17 /LD /O2 /MT /Ilibs\sqlite src\chrome_decrypt.cpp src\reflective_loader.c "sqlite3_x64.lib" bcrypt.lib ole32.lib oleaut32.lib shell32.lib version.lib comsuppw.lib /link /OUT:"chrome_decrypt_x64.dll"
-          if not exist "chrome_decrypt_x64.dll" exit 1
+          if not exist "chrome_decrypt_x64.dll" (
+            echo "Error: chrome_decrypt_x64.dll not found!"
+            dir .
+            exit 1
+          )
           echo "chrome_decrypt.dll compilation finished"
 
       - name: Compile resource script
@@ -44,8 +48,13 @@ jobs:
         run: |
           echo "Compiling resource.rc"
           echo CHROME_DECRYPT_DLL RCDATA "chrome_decrypt_x64.dll" > resource.rc
+          dir chrome_decrypt_x64.dll
           rc /v resource.rc
-          if not exist "resource.res" exit 1
+          if not exist "resource.res" (
+            echo "Error: resource.res not found!"
+            dir .
+            exit 1
+          )
           echo "Resource compilation finished"
 
       - name: Compile chrome_inject.exe (x64)
@@ -53,7 +62,11 @@ jobs:
         run: |
           echo "Compiling chrome_inject.exe for x64"
           cl /EHsc /O2 /std:c++17 /MT src\chrome_inject.cpp version.lib shell32.lib resource.res /link /OUT:"chrome_inject_x64.exe"
-          if not exist "chrome_inject_x64.exe" exit 1
+          if not exist "chrome_inject_x64.exe" (
+            echo "Error: chrome_inject_x64.exe not found!"
+            dir .
+            exit 1
+          )
           echo "chrome_inject.exe compilation finished"
 
       - name: Create Artifacts Directory
